/*Copyright (c) 2016-2017 testing1.com All Rights Reserved.
 This software is the confidential and proprietary information of testing1.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with testing1.com*/

package com.test_21.qadatabase.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.test_21.qadatabase.*;

/**
 * Service object for domain model class Table7.
 * @see com.test_21.qadatabase.Table7
 */

public interface Table7Service {
   /**
	 * Creates a new table7.
	 * 
	 * @param created
	 *            The information of the created table7.
	 * @return The created table7.
	 */
	public Table7 create(Table7 created);

	/**
	 * Deletes a table7.
	 * 
	 * @param table7Id
	 *            The id of the deleted table7.
	 * @return The deleted table7.
	 * @throws EntityNotFoundException
	 *             if no table7 is found with the given id.
	 */
	public Table7 delete(Integer table7Id) throws EntityNotFoundException;

	/**
	 * Finds all table7s.
	 * 
	 * @return A list of table7s.
	 */
	public Page<Table7> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<Table7> findAll(Pageable pageable);
	
	/**
	 * Finds table7 by id.
	 * 
	 * @param id
	 *            The id of the wanted table7.
	 * @return The found table7. If no table7 is found, this method returns
	 *         null.
	 */
	public Table7 findById(Integer id) throws
	 EntityNotFoundException;
	/**
	 * Updates the information of a table7.
	 * 
	 * @param updated
	 *            The information of the updated table7.
	 * @return The updated table7.
	 * @throws EntityNotFoundException
	 *             if no table7 is found with given id.
	 */
	public Table7 update(Table7 updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the table7s in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the table7.
	 */

	public long countAll();


    public Page<Table7> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

