/*Copyright (c) 2016-2017 testing1.com All Rights Reserved.
 This software is the confidential and proprietary information of testing1.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with testing1.com*/

package com.test_21.qadatabase.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.test_21.qadatabase.*;

/**
 * Service object for domain model class Table6.
 * @see com.test_21.qadatabase.Table6
 */

public interface Table6Service {
   /**
	 * Creates a new table6.
	 * 
	 * @param created
	 *            The information of the created table6.
	 * @return The created table6.
	 */
	public Table6 create(Table6 created);

	/**
	 * Deletes a table6.
	 * 
	 * @param table6Id
	 *            The id of the deleted table6.
	 * @return The deleted table6.
	 * @throws EntityNotFoundException
	 *             if no table6 is found with the given id.
	 */
	public Table6 delete(Integer table6Id) throws EntityNotFoundException;

	/**
	 * Finds all table6s.
	 * 
	 * @return A list of table6s.
	 */
	public Page<Table6> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<Table6> findAll(Pageable pageable);
	
	/**
	 * Finds table6 by id.
	 * 
	 * @param id
	 *            The id of the wanted table6.
	 * @return The found table6. If no table6 is found, this method returns
	 *         null.
	 */
	public Table6 findById(Integer id) throws
	 EntityNotFoundException;
	/**
	 * Updates the information of a table6.
	 * 
	 * @param updated
	 *            The information of the updated table6.
	 * @return The updated table6.
	 * @throws EntityNotFoundException
	 *             if no table6 is found with given id.
	 */
	public Table6 update(Table6 updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the table6s in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the table6.
	 */

	public long countAll();


    public Page<Table6> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

